SELECT * FROM public.vw_processos_datajud;
SELECT * FROM public.vw_processos_assuntos;
SELECT * FROM public.vw_processos_movimentos;
SELECT * FROM public.vw_processos_movimentos_complementos;
SELECT * FROM public.vw_processos_movimentos_orgao;
SELECT * FROM public.vw_processos_classe;
SELECT * FROM public.vw_processos_sistema;
SELECT * FROM public.vw_processos_formato;
SELECT * FROM public.vw_processos_orgao_julgador;
