SELECT * FROM public.vw_processos_datajud;
SELECT * FROM public.vw_processos_datajud_glossario;
SELECT * FROM public.vw_processos_datajud_flat;
SELECT * FROM public.vw_processos_assuntos;
SELECT * FROM public.vw_processos_movimentos;
SELECT * FROM public.vw_processos_classe;
SELECT * FROM public.vw_processos_sistema;
SELECT * FROM public.vw_processos_formato;
SELECT * FROM public.vw_processos_orgao_julgador;
